name: "Download Release Assets"
description: "Download assets from Github Release"
author: "Vinayak Jadhav"

inputs:
  gh-token:
    description: "Github Token or Pat Token"
    required: true
  release-tag:
    description: "Release Tag"
    required: true
  asset-names:
    description: "Name of the asset to download"
    required: true
  path:
    description: "Destination path. Defaults to $GITHUB_WORKSPACE"
    required: false
  repository:
    description: "The repository owner and the repository name joined together by /"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "white"